sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t nmannaii/react-docker .
script:
  - docker run nmannaii/react-docker npm run test -- --coverage --watchAll=false